first_sign = "equal"
second_sign ="plus"
puts "welcome to ruby\b"
puts "This is a \"double quote\" within double quotes."
puts "I am a ruby \nby a line."
puts "\v vertical tab before me."
puts "Here is an #{first_sign} in octal code: \075"
puts "Here is an #{second_sign} in Hex code: \x2B"
puts "The answer to 5 + 2 is \n#{5+2}"
